# Generated by Django 5.2.2 on 2025-06-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDavlati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorydavlati', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CJanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryjanr', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CKino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorykino', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CTili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorytili', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('banner', models.ImageField(upload_to='meida/')),
                ('release_date', models.DateField()),
                ('video', models.FileField(upload_to='videos/')),
                ('sarlavha', models.CharField(max_length=200)),
                ('davomiyligi', models.CharField(max_length=100, null=True)),
                ('categorydavlati', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asilmedia.cdavlati')),
                ('categoryjanr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asilmedia.cjanr')),
                ('categorykinolar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asilmedia.ckino')),
                ('categorytili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asilmedia.ctili')),
            ],
        ),
    ]
