# Generated by Django 5.2.2 on 2025-06-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asilmedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='categorykinolar',
        ),
        migrations.RemoveField(
            model_name='cdavlati',
            name='categorydavlati',
        ),
        migrations.RemoveField(
            model_name='cjanr',
            name='categoryjanr',
        ),
        migrations.RemoveField(
            model_name='ctili',
            name='categorytili',
        ),
        migrations.AddField(
            model_name='cdavlati',
            name='cdavlati',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cjanr',
            name='cjanr',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ctili',
            name='ctili',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='banner',
            field=models.ImageField(null=True, upload_to='meida/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='sarlavha',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.DeleteModel(
            name='CKino',
        ),
    ]
